# Generated by Django 3.2.16 on 2022-12-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, help_text='Enter type of yoga', max_length=200, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
